package com.radial.fraudmanagement;

import com.radial.fraudmanagement.IPAddress;
import com.radial.fraudmanagement.Order;
import com.radial.fraudmanagement.FraudRequest;
import com.radial.fraudmanagement.LineItem;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

function boolean isProductNameContain(Order pOrder) {
    boolean status = false;
    if(null != pOrder && null != pOrder.lineItems && null != pOrder.lineItems.lineItem
    && pOrder.lineItems.lineItem.size() > 0) {
        int count = 0;
        for(LineItem item: pOrder.lineItems.lineItem) {
            if(null != item.name && containsCaseInsensitive(item.name)) {
                count++;
            }
        }
        if(count == pOrder.lineItems.lineItem.size()) {
            status = true;
        }
    }
    return status;
}

function boolean isShippingMethodExist(Order pOrder) {
    boolean status = false;
    if(null != pOrder && null != pOrder.shippingInfo && null != pOrder.shippingInfo.shippingMethod &&
    (pOrder.shippingInfo.shippingMethod.equalsIgnoreCase("ground") || pOrder.shippingInfo.shippingMethod.equalsIgnoreCase("2nd day"))) {
        status = true;
    }
    return status;
}

rule "Rule2 ProductNameDoesNotContain"
	dialect "java"
	salience 4
	when
		fraud:Fraud(null != Fraud.fraudRequest, !isProductNameContain(Fraud.fraudRequest.order))
	then
	    AuditTrail trail = new AuditTrail();
	    trail.setScore(100);
	    trail.setRule("Rule2 ProductNameDoesNotContain");
	    trail.setAction("None");
	    trail.setNotes("Does not meet Product Name");
	    fraud.getAudit().getAuditTrail().add(trail);
	    System.out.println("score:::"+ fraud.getAudit().getTotalScore());
		insert( fraud );
end

rule "Rule2 ShippingMethod"
	dialect "java"
	salience 3
	when
		fraud:Fraud(null != Fraud.fraudRequest, !isShippingMethodExist(Fraud.fraudRequest.order))
	then
	    AuditTrail trail = new AuditTrail();
	    trail.setScore(100);
	    trail.setRule("Rule2 ShippingMethod");
	    trail.setAction("None");
	    trail.setNotes("Does not meet Shipping Method");
	    fraud.getAudit().getAuditTrail().add(trail);
	    System.out.println("score:::"+ fraud.getAudit().getTotalScore());
		insert( fraud );
end

rule "Rule2 MeetsAllCriteria"
	dialect "java"
	salience 2
	when
		fraud:Fraud(null != Fraud.fraudRequest, isShippingMethodExist(Fraud.fraudRequest.order),
		        isProductNameContain(Fraud.fraudRequest.order))
	then
	    AuditTrail trail = new AuditTrail();
	    trail.setScore(-200);
	    trail.setRule("Rule2 MeetsAllCriteria");
	    trail.setAction("Held for Screening");
	    trail.setNotes("Meets all conditions");
	    fraud.getAudit().getAuditTrail().add(trail);
	    System.out.println("score:::"+ fraud.getAudit().getTotalScore());
		insert( fraud );
end

