package com.radial.fraudmanagement;

import com.radial.fraudmanagement.IPAddress;

function boolean isNullIP(IPAddress ip) {
    boolean status=false;
    if(null == ip || null == ip.countryName || null == ip.countryName.code) {
        status=true;
    }
    return status;
}

rule "Rule1 NullIP"
	dialect "java"
	when
		fraud:Fraud(null != Fraud.fraudRequest, isNullIP(Fraud.fraudRequest.ipAddress))
	then
	    AuditTrail trail = new AuditTrail();
	    trail.setScore(100);
	    trail.setRule("Rule1 NullIP");
	    trail.setAction("None");
	    trail.setNotes("Null IP, rule should not fire");
	    fraud.getAudit().getAuditTrail().add(trail);
	    System.out.println("request:::"+fraud.fraudRequest);
	    System.out.println("score:::"+ fraud.getAudit().getTotalScore());
		insert( fraud );
end

