package com.radial.fraudmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CostTotals implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CostTotals() {
    }

}