package com.radial.fraudmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FraudRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;

   public FraudRequest()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public FraudRequest(java.lang.String id)
   {
      this.id = id;
   }

}