package com.radial.fraudmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FraudRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;

   private com.radial.fraudmanagement.Order order;

   public FraudRequest()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public com.radial.fraudmanagement.Order getOrder()
   {
      return this.order;
   }

   public void setOrder(com.radial.fraudmanagement.Order order)
   {
      this.order = order;
   }

   public FraudRequest(java.lang.String id, com.radial.fraudmanagement.Order order)
   {
      this.id = id;
      this.order = order;
   }

}