package com.radial.fraudmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LineItem implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public java.lang.String lineItemId;
   public java.lang.Float unitCost;
   public int quantity;
   public java.lang.String name;

   public LineItem()
   {
   }

   public java.lang.String getLineItemId()
   {
      return this.lineItemId;
   }

   public void setLineItemId(java.lang.String lineItemId)
   {
      this.lineItemId = lineItemId;
   }

   public java.lang.Float getUnitCost()
   {
      return this.unitCost;
   }

   public void setUnitCost(java.lang.Float unitCost)
   {
      this.unitCost = unitCost;
   }

   public int getQuantity()
   {
      return this.quantity;
   }

   public void setQuantity(int quantity)
   {
      this.quantity = quantity;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public LineItem(java.lang.String lineItemId, java.lang.Float unitCost,
         int quantity, java.lang.String name)
   {
      this.lineItemId = lineItemId;
      this.unitCost = unitCost;
      this.quantity = quantity;
      this.name = name;
   }

}