package com.radial.fraudmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String orderID;

   public Order()
   {
   }

   public java.lang.String getOrderID()
   {
      return this.orderID;
   }

   public void setOrderID(java.lang.String orderID)
   {
      this.orderID = orderID;
   }

   public Order(java.lang.String orderID)
   {
      this.orderID = orderID;
   }

}