package com.radial.fraudmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Persons implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private com.radial.fraudmanagement.Person person;

   public Persons()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public com.radial.fraudmanagement.Person getPerson()
   {
      return this.person;
   }

   public void setPerson(com.radial.fraudmanagement.Person person)
   {
      this.person = person;
   }

   public Persons(java.lang.String id, com.radial.fraudmanagement.Person person)
   {
      this.id = id;
      this.person = person;
   }

}