package com.radial.fraudmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TotalCost implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private com.radial.fraudmanagement.Address address;
   private com.radial.fraudmanagement.PersonName personName;
   private java.lang.String email;

   public TotalCost()
   {
   }

   public com.radial.fraudmanagement.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(com.radial.fraudmanagement.Address address)
   {
      this.address = address;
   }

   public com.radial.fraudmanagement.PersonName getPersonName()
   {
      return this.personName;
   }

   public void setPersonName(com.radial.fraudmanagement.PersonName personName)
   {
      this.personName = personName;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public TotalCost(com.radial.fraudmanagement.Address address,
         com.radial.fraudmanagement.PersonName personName,
         java.lang.String email)
   {
      this.address = address;
      this.personName = personName;
      this.email = email;
   }

}